FROM ubuntu:22.04

FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Cài đặt các công cụ cần thiết và ttyd
RUN apt-get update && apt-get install -y \
    ftp lftp openssh-client curl wget netcat nmap vim nano \
    net-tools iputils-ping dnsutils cmake git libjson-c-dev \
    libwebsockets-dev gcc make \
    && rm -rf /var/lib/apt/lists/*

# Build ttyd
RUN git clone --depth=1 https://github.com/tsl0922/ttyd.git /tmp/ttyd \
    && cd /tmp/ttyd && mkdir build && cd build \
    && cmake .. && make && make install \
    && rm -rf /tmp/ttyd

WORKDIR /root

COPY entrypoint-client.sh /entrypoint-client.sh
RUN chmod +x /entrypoint-client.sh

# Entrypoint sẽ xử lý việc lấy biến ENV
ENTRYPOINT ["/entrypoint-client.sh"]
