#!/bin/bash
set -e

echo "🌐 IDOR Lab Web Server Starting..."

# Wait a bit for FLAG_INFO.json to be generated by DB container
sleep 2

# FLAG_INFO.json is hidden now
# if [ -f /flag-data/FLAG_INFO.json ]; then
#     cp /flag-data/FLAG_INFO.json /var/www/html/FLAG_INFO.json 2>/dev/null || true
#     echo "✅ FLAG info available at /FLAG_INFO.json"
# fi

echo "🚀 Starting Apache..."

# Start Apache
exec apache2-foreground
